// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZaff1ykUp7qKdbvp2cnGlOSS0ZxsnKDQ',
    appId: '1:592796748140:web:4cd926fb30e3694df74b49',
    messagingSenderId: '592796748140',
    projectId: 'contacts-phone',
    authDomain: 'contacts-phone.firebaseapp.com',
    storageBucket: 'contacts-phone.firebasestorage.app',
    measurementId: 'G-TX3MX1ZL8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSOeGa7l5OhxgbYhRau8odknU8zcpcdBI',
    appId: '1:592796748140:android:4ffe1dfc3401d44af74b49',
    messagingSenderId: '592796748140',
    projectId: 'contacts-phone',
    storageBucket: 'contacts-phone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChoW4pujTeXNfX9RdvCPvFdSuRqRJ0XnA',
    appId: '1:592796748140:ios:84740f5ccb18f957f74b49',
    messagingSenderId: '592796748140',
    projectId: 'contacts-phone',
    storageBucket: 'contacts-phone.firebasestorage.app',
    iosBundleId: 'com.example.contactsPhone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChoW4pujTeXNfX9RdvCPvFdSuRqRJ0XnA',
    appId: '1:592796748140:ios:84740f5ccb18f957f74b49',
    messagingSenderId: '592796748140',
    projectId: 'contacts-phone',
    storageBucket: 'contacts-phone.firebasestorage.app',
    iosBundleId: 'com.example.contactsPhone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZaff1ykUp7qKdbvp2cnGlOSS0ZxsnKDQ',
    appId: '1:592796748140:web:1b8294d0493435e4f74b49',
    messagingSenderId: '592796748140',
    projectId: 'contacts-phone',
    authDomain: 'contacts-phone.firebaseapp.com',
    storageBucket: 'contacts-phone.firebasestorage.app',
    measurementId: 'G-9BS9J99HE5',
  );
}
